# Generated by Django 5.2.6 on 2025-11-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_item_starting_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='numerical_rating',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')]),
        ),
    ]
