# Generated by Django 5.2.6 on 2025-11-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_review_numerical_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='numerical_rating',
            field=models.IntegerField(choices=[(1, 'Rate 1 Stars'), (2, 'Rate 2 Stars'), (3, 'Rate 3 Stars'), (4, 'Rate 4 Stars'), (5, 'Rate 5 Stars')]),
        ),
    ]
